### ISSUE TITLE
a

### ISSUE THREAD

**Issue by ilightwas** [stdiopt/stream#2]

**Comment by stdiopt** [comment]
???

**Comment by ilightwas** [comment]
Aqui é o Sam, a gente jogou project torque muitos anos atras. Depois acho que tu ficou viciado no tal do planetside, pilotando as naves lá. Perdi teu contato, passa teu discord ai pra gnt se conectar de novo

**Comment by ilightwas** [comment]
@stdiopt add no discord quando ver aqui

ilightwas#3092
